### PR TITLE
Fixes and Tests for PolarsMixin

### PR DESCRIPTION
**Pull request by adamamer20**
This PR fixes the logic of many `PolarsMixin` methods and adds tests for all methods.

### CODE REVIEW

**Review by rht — APPROVED** [review]

**Comment by rht** [comment]
Did you use polars-upgrade for any of the changes in this PR?

**Comment by adamamer20** [comment]
> Did you use polars-upgrade for any of the changes in this PR?

No, just something for the future. It's pretty new, so I have to assess stability.

**Comment by rht** [comment]
I'm not familiar with Polars API at the moment, so I approve the PR so as not to block you.

**Comment by adamamer20** [comment]
> I'm not familiar with Polars API at the moment, so I approve the PR so as not to block you.

No problem, we can always evaluate performance later. I'll just add tests for missing lines.

**Pull request merged**
