### PR TITLE
Adding SugarScape IG (polars with loops)

### PR DESCRIPTION
**Pull request by adamamer20**
This PR adds the Sugarscape IG implementation with AgentSetPolars and GridPolars.

@rht: Sorry but I made a mistake with the last performance plot. It measured allocation/setup but not the actual running of the model. The good news is that mesa-frames with Polars still scales better than native Python, as can be seen from the plot, though not as well as flame2gpu (with the CPU implementation, that is - it simply doesn't scale as well).
The implementation can still be made faster with some simple tweaks (e.g., lazy query and GridPolars implementation with pl.ranges), but I think there's not much time to optimize it further before GSoC ends.
The bad news is that pandas scales horribly, and this probably has to do with DFs being the size of RAM or larger (I am doing some profiling right now to understand), which pandas really struggles to handle. I am thinking of a solution (e.g., using Dask, which should have the same API), but I will keep you posted.

### CODE REVIEW

**Comment by rht** [comment]
> The bad news is that pandas scales horribly, and this probably has to do with DFs being the size of RAM or larger (I am doing some profiling right now to understand), which pandas really struggles to handle. 

Can I take a look at the current pandas result?

**Comment by adamamer20** [comment]
> > The bad news is that pandas scales horribly, and this probably has to do with DFs being the size of RAM or larger (I am doing some profiling right now to understand), which pandas really struggles to handle. 
> 
> Can I take a look at the current pandas result?

Sorry, been working on API docs. Tomorrow I will send you the graphs.

**Comment by adamamer20** [comment]
UPDATE:
1) Dask and Dask-cuDF require significant refactoring. It can be added as a backend in the future but it's not a possible solution right now.
2) cuDF does not have the combine_first method implemented (so we need to reimplement it with other cuDF operations or it will fallback to pandas). Most of the time in cuDF is also spent on merge operations. I need to dig deeper because it seems weird that merge requires so much time, even more on GPU where it should be faster.
3) This is the best approach right now: it does not require a significant refactoring and should speed up operations. I'm working on it in `unique-agents-cells-space`

**Review by rht — APPROVED** [review]

**Comment by rht** [comment]
> Dask and Dask-cuDF require significant refactoring. It can be added as a backend in the future but it's not a possible solution right now.

Will the refactoring complicate the implementation, or is it mainly replacing the ops to the ones supported by Dask/Dask-cuDF?

**Comment by adamamer20** [comment]
> > Dask and Dask-cuDF require significant refactoring. It can be added as a backend in the future but it's not a possible solution right now.
> 
> Will the refactoring complicate the implementation, or is it mainly replacing the ops to the ones supported by Dask/Dask-cuDF?

Just a matter of implementing operations with DaskMixin, implementation should stay the same.

**Comment by adamamer20** [comment]
I will merge this PR and open a dedicate issue for Pandas speedup (and DaskMixin).

**Pull request merged**
